build_sh: Try to use LD=ld.lld
Without this commit, when you building kernel, in the last the build system will give you some errors like this:
`
  LD      drivers/usb/gadget/function/built-in.o
  LD      drivers/usb/gadget/built-in.o
  CC      drivers/usb/serial/usb-serial.o
  CC      drivers/usb/serial/generic.o
  CC      drivers/usb/phy/of.o
  LD      drivers/usb/pd/built-in.o
  CC      drivers/usb/storage/uas.o
  CC      drivers/usb/phy/class-dual-role.o
  CC      drivers/usb/storage/scsiglue.o
  CC      drivers/usb/serial/bus.o
  CC      drivers/usb/phy/phy-generic.o
  CC      drivers/usb/storage/protocol.o
  CC      drivers/usb/storage/transport.o
  CC      drivers/usb/serial/cp210x.o
  CC      drivers/usb/phy/phy-msm-ssusb-qmp.o
  CC      drivers/usb/storage/usb.o
  CC      drivers/usb/serial/ftdi_sio.o
  CC      drivers/usb/storage/initializers.o
  CC      drivers/usb/phy/phy-msm-qusb.o
  CC      drivers/usb/storage/sierra_ms.o
  CC      drivers/usb/storage/option_ms.o
  LD      drivers/usb/serial/usbserial.o
  LD      drivers/usb/serial/built-in.o
  CC      drivers/usb/storage/usual-tables.o
  CC      drivers/usb/phy/phy-msm-qusb-v2.o
  LD      drivers/usb/storage/usb-storage.o
  LD      drivers/usb/storage/built-in.o
  LD      drivers/usb/phy/built-in.o
  LD      drivers/usb/built-in.o
  LD      drivers/built-in.o
  GEN     .version
  LD      vmlinux.o
  MODPOST vmlinux.o
WARNING: modpost: Found 2 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
drivers/built-in.o: In function `qpnp_adc_tm_probe':
rules.c:(.text+0x6ab83c): undefined reference to `ht_register_thermal_zone_device'
drivers/built-in.o: In function `tsens_tm_probe':
rules.c:(.text+0x6ae3c8): undefined reference to `ht_register_thermal_zone_device'
make[1]: *** [/home/runner/work/android_kernel_github_workflow/android_kernel_github_workflow/android-kernel/Makefile:1129: vmlinux] Error 1
make[1]: Leaving directory '/home/runner/work/android_kernel_github_workflow/android_kernel_github_workflow/android-kernel/out'
make: *** [Makefile:152: sub-make] Error 2
"

Now, ld.lld is trashed. This question is caused by these config:

- CONFIG_THERMAL_TSENS
- CONFIG_THERMAL_QPNP_ADC_TM